name: {{name}}
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  get_it: ^7.2.0
  provider: ^6.0.3
  flutter_bloc: ^8.0.1
  intl: ^0.17.0
  go_router: ^4.1.0
  flutter_hooks: ^0.18.5+1
  freezed_annotation: ^2.0.3

  infinite_scroll_pagination:
    git: https://github.com/HaijunWei/infinite_scroll_pagination.git
  custom_refresh_indicator:
    git: https://github.com/HaijunWei/flutter-custom-refresh-indicator.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.0.3+1
  build_runner:
  json_serializable: 
  flutter_gen_runner: 
  icons_launcher: ^1.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    
flutter_intl:
  enabled: true

flutter_gen:
  output: lib/support_files/
  line_length: 80